### ISSUE TITLE
Showcase video fullscreen buttons dont work, when enter fullscreen via click on video image

### ISSUE THREAD

**Issue by oxplay2** [jMonkeyEngine/jmonkeyengine-website#13]
like in topic:

Steps:
1) enter https://jmonkeyengine.org/showcase/ls_frontier/
2) scroll right to video (8-th)
3) click on video image (when it play or to start play, both have same)
4) click on "fullscreen button" image below:
![image](https://user-images.githubusercontent.com/45903579/102073194-41852180-3e03-11eb-8c25-0ec344b6066e.png)
5) this button do nothing.
6) use ESC to quit fullscreen mode
7) click this button again and see it work when used first "out-of-fullscreen-mode"

**Comment by riccardobl** [comment]
Should be fixed in https://github.com/jMonkeyEngine/jmonkeyengine-website/commit/56a9027205c6e7ccf312caf038c05afe4d08d6e2
