### ISSUE TITLE
Forum blog button directs to outdated page

### ISSUE THREAD

**Issue by DGC9Crew** [jMonkeyEngine/jmonkeyengine-website#15]
On the [jMonkey forum](https://hub.jmonkeyengine.org/), the user blog button under the navigation button goes to https://jmonkeyengine.org/blog/, which is just an XML tree of the previous website blog.

It needs to be updated to direct to the blog for the new website, I think https://jmonkeyengine.org/tags/blog/ would work.

(not entirely sure if this is where I should report the issue, but it's related to the new website)

**Comment by riccardobl** [comment]
Fixed with https://github.com/jMonkeyEngine/jmonkeyengine-website/commit/44c0ed60a9ac1c1ffb61821d26eeb76c1038b0cb
