### ISSUE TITLE
There is no method getCurrentAction() in AnimComposer.class

### ISSUE THREAD

**Issue by AlexandrPutenikhin** [jMonkeyEngine/jmonkeyengine-website#18]
![Screenshot_38](https://user-images.githubusercontent.com/88931618/129445208-128514f0-ba7e-4350-948d-2effcfd49f51.png)
(Only SDK)

**Comment by stephengold** [comment]
I don't understand how this is a website issue.

It's true that there was no `getCurrentAction()` in JMonkeyEngine v3.3. It was added in v3.4.0, which is the latest release. Here's the pull request which added it:

https://github.com/jMonkeyEngine/jmonkeyengine/pull/1376

If you need technical support, please join the JMonkeyEngine Forum/Hub and post your question there:  https://hub.jmonkeyengine.org/
